site_url: https://sawtooth.netlify.app/
display_url: https://sawtooth.netlify.app/
backend:
  name: git-gateway
  branch: master
media_folder: src/static/images
public_folder: /images
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "New Post"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Wikipedia Url", name: "url", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "relation", collection: "images", search_fields: ["slug"], value_field: "{{slug}}", display_fields: ["slug"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "images"
    label: "Images"
    label_singular: "New Image"
    folder: "src/content/images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Credit", name: "credit", widget: "string" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - { label: "Source", name: "source", widget: "string" }