site_url: https://sawtooth.netlify.app/
display_url: https://sawtooth.netlify.app/
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "New Post" # Used in the UI, ie: "New Post"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Wiki Link", name: "url", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "images"
    label: "Images"
    label_singular: "New Image" # Used in the UI, ie: "New Post"
    folder: "content/images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Credit", name: "credit", widget: "string" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - { label: "Source", name: "source", widget: "string" }